### PR TITLE
Ewlj 144 print style sheets

### PR DESCRIPTION
**Pull request by aCyborg**
## Ticket(s)

**Github Issue**

N/A

**Jira Ticket**

- [EWLj-144: Print Style Sheet](https://issues.ama-assn.org/browse/EWLJ-144)

## Description

Creates a basic print style sheet.

## To Test

- [ ] Spin up Patternlab
- [ ] Review each page. First by opening in a new window, and then either with print emulation, reviewing in the print preview window, or actually printing the page.

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

### CODE REVIEW

**Comment by gleroux02** [comment]
@aCyborg are you seeing the word "Menu" displaying in the far left sidebar? 
image

**Comment by gleroux02** [comment]
[Pattern Lab - pages-homepage.pdf](https://github.com/palantirnet/ama-style-guide-joe/files/1732877/Pattern.Lab.-.pages-homepage.pdf)
I'm seeing some odd issues.

**Comment by aCyborg** [comment]
@gleroux02 
Can you 'open in new window' using the little settings icon in the top right corner of patternlab?

The patternlab iframe kind of messes with printing so you have to view them all as standalones.

**Review by gleroux02 — APPROVED** [review]
👍 this looks good. Going to merge.

**Pull request merged**
